@ECHO OFF

SET SDL_INCLUDE_PATH=C:/Lib/SDL2/include
SET GLAD_INCLUDE_PATH=C:/Lib/glad/include
SET GLM_INCLUDE_PATH=C:/Lib/glm
SET MY_INCLUDE_PATH=C:/Users/spide/Desktop/mc/include

SET SDL_LIB_PATH=C:/Lib/SDL2/lib
SET GLAD_SRC=C:/Lib/glad/src/glad.c

SET FLAGS=-lmingw32 -lSDL2main -lSDL2 -O2

SET FILES=src/*.cpp

SET APP_NAME=mc

g++ %FILES% %GLAD_SRC% -o %APP_NAME% -I%SDL_INCLUDE_PATH% -I%GLAD_INCLUDE_PATH% -I%GLM_INCLUDE_PATH% -I%MY_INCLUDE_PATH% -L%SDL_LIB_PATH% %FLAGS%